import type { NextPage } from 'next';
import Head from 'next/head';
import LandingPage from '@/components/LandingPage';

import styles from '@/styles/Main.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.mainContainer}>
			<Head>
				<title>Adam Serpa Music</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
        <LandingPage />
			</main>
    </div>
  );
};

export default Home;
